[Environment]
envelope = { shape = "box", padding = [ 0, 0, 0, 0, 0, 3e4 ] }

[Environment.Terrain]
mesh = { path = "meshes/terrain.png", units = "m", padding = 200 }
material = "SomeRock"

[materials.mixtures]
SomeRock = { density = 2.0, state = "solid", composition = { StandardRock = 1 }}
